### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by yoyo-gong**
- fixed the bugs so that the user can be directed to home page after successfully log in
- added password requirements
- added log out function

### CODE REVIEW

**Comment by jameschenyung** [comment]
There are some conflicting files on my end, please take a look at that, thanks!

**Comment by jasmine528wangf** [comment]
Maybe solve the ".idea/.gitignore
.idea/libraries/jar_files.xml
.idea/misc.xml
.idea/modules.xml" conflicts before merging.

**Comment by yoyo-gong** [comment]
I have resolved the conflicts in the .idea files.

**Review by KeiserJ — APPROVED** [review]
good job solving the conflict

**Pull request merged**
